### ISSUE TITLE
otl2html should recognize URLs

### ISSUE THREAD

**Issue by mcepl** [vimoutliner/vimoutliner#115]
It would be lovely if `otl2html` recognized URLs in the outline and marked them as `<a>` element.

**Comment by noelhenson** [comment]
otl2html already has a 'link' syntax.

**Comment by mcepl** [comment]
> otl2html already has a 'link' syntax.

OK, then I plead stupid ... how one does create a construct in the `.otl` file which would get changed into `<a>` element? I thought
```
_exe_ name URL
```
is the way, but it doesn't seem to create anything for me.
```
matej@mitmanek: ~$ cat test.otl 
Ubytování, dovolená JZ Čechy 2015
	_exe_ OSM http://osm.org/go/0JwHYnh--?node=2390161317
matej@mitmanek: ~$ otl2html -S /dev/null test.otl
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"s
        "http://www.w3.org/TR/html4/strict.dtd">
    <html><head><title>Ubytování, dovolená JZ Čechy 2015</title></head>
<style type="text/css">
</style></head>
<body>
<div class="DocTitle">
    <h1>Ubytování, dovolená JZ Čechy 2015</h1>
    </div>
    <div class="MainPage">
<ol>
<li  class="L1" >_exe_ OSM http://osm.org/go/0JwHYnh--?node=2390161317 </ol>
</div>
<div class="Footer">
<hr>

<br>
test.otl&nbsp&nbsp 2015/06/01 08:59
</div>
</body></html>
matej@mitmanek: ~$ 
```

**Comment by noelhenson** [comment]
It appears that the otl2html help has been removed from VO. Let me see 
what I can find in my archives.

**Comment by noelhenson** [comment]
otl2tags is also useful but needs a little bit of love. It can create 
web pages as well.

**Comment by noelhenson** [comment]
OK. Try 'otl2html.py -H' for some quick help. Most people don't really 
use the --help option anymore. ;)

**Comment by noelhenson** [comment]
Here  is a working example. It's my old website, created in a single OTL 
file. I Hope that helps.



On 06/01/2015 01:59 AM, Matěj Cepl wrote:
>
>     otl2html already has a 'link' syntax.
>
> OK, then I plead stupid ... how one does create a construct in the 
> |.otl| file which would get changed into |<a>| element? I thought
>
> |_exe_ name URL
> |
>
> is the way, but it doesn't seem to create anything for me.
>
> |matej@mitmanek: ~$ cat test.otl
> Ubytování, dovolená JZ Čechy 2015
>      _exe_ OSM http://osm.org/go/0JwHYnh--?node=2390161317
> matej@mitmanek: ~$ otl2html -S /dev/null test.otl
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"s
>          "http://www.w3.org/TR/html4/strict.dtd">
>      <html><head><title>Ubytování, dovolená JZ Čechy 2015</title></head>
> <style type="text/css">
> </style></head>
> <body>
> <div class="DocTitle">
>      <h1>Ubytování, dovolená JZ Čechy 2015</h1>
>      </div>
>      <div class="MainPage">
> <ol>
> <li  class="L1" >_exe_ OSM http://osm.org/go/0JwHYnh--?node=2390161317 </ol>
> </div>
> <div class="Footer">
> <hr>
>
> <br>
> test.otl&nbsp&nbsp 2015/06/01 08:59
> </div>
> </body></html>
> matej@mitmanek: ~$
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vimoutliner/vimoutliner/issues/115#issuecomment-107330485>.
>


all :
	otlsplit -l 1 -D exports website.otl ; \
	cp otl*.otl exports
	cp crlf.otl exports
	cp easy*.otl exports
	cp cidr*.otl exports
	cp cordic.otl exports
	cp forthstrings.otl exports
	cd exports && make $@

clean :
	rm -f *~
	cd exports && make $@

upload :
#	rsync -vv -t exports/*.html exports/*.css noel@noels-lab.com:httpdocs
	./upload

Noel's Lab
Index
	Noel's Lab #Noel's Lab: MCUs, circuits, programming, thinking and gadgetry.#
	_Menu
		//Home//
		[blog.html Blog]
		[reviews.html Reviews]
		[howtos.html HOWTOs]
		[software.html Software]
		[links.html Links]
		[contact.html Contact]
	News
		//March 12th, 2012//
			Journey Val ROCKS!!!
				: Yep. she really does.
		//December 10th, 2009//
			Added Forth Strings Library
				: I have uploaded my old Forth-79/Forth-83 strings library 
				: from the late '80s. It has been updated to work with modern 
				: Forths like GFORTH.
				:
				: [+http://www.noels-lab.com/forthstrings.html Forth Strings Library]
		//January 1st, 2007//
			EasyBackup Added to Software
				: I've finally uploaded a useful version of my easybackup.sh 
				: script. Backing up data is a great thing to do at the 
				: beginning of a new year.
				:
				: [+http://www.noels-lab.com/easybackup.html easybackup.sh]
				:
				: Happy New Year!
				:
				: Noel
		//October 15th, 2006//
			CORDIC Demo Added
				: I've added a demo CORDIC program to compute basic trig 
				: functions. It's written in Forth and should be easy to 
				: understand and port to other languages. The implementation 
				: is simple and efficient enough to use on small MCUs.
				: 
				: [+http://www.noels-lab.com/cordic.html CORDIC Demo]
				:
				: Have fun with it!
				:
				: Noel
		//February 20th, 2006//
			Open-source utilities added
				: I've put up the open-source software I've created for my own 
				: use. You can find it in the new [software.html Software] 
				: section. Most have to do with outlining using 
				: [http://www.vimoutliner.org Vim Outliner]. Feel free to 
				: (ab)use them as you see fit (as long as you honor the GPL).
				:
				: Noel
		//October 22nd, 2005//
			Lane Mountain Logic spins-off from Noel's Lab
				: Website traffic over the last year has shown two major 
				: audiences for Noel's Lab. The first is hobbyists, students 
				: and experimenters. The second group is comprised mainly of 
				: businesses seeking professional services. 
				:
				: If you're in the first group, congratulations. You have 
				: chosen a fun, interesting and growing field of study. Noel's 
				: Lab will continue to serve you in these endeavors. In fact 
				: Noel's Lab is dropping all products and services so it can 
				: more spend more time working with the 
				: electronics/embedded/thinking communities.
				:
				: If you're in the second group, you'll want to move along to 
				: [http://www.lmlogic.com Lane Mountain Logic]. There you can 
				: find circuit design, MCU programming and other engineering 
				: services.
				:
				: Please don't hesitate to let me know what you'd like to see.
	_BottomMenu
		[index.html Home] :: [blog.html Blog] :: [reviews.html Reviews] :: [howtos.html HOWTOs] :: [software.html Software] :: [links.html Links] :: [contact.html Contact]
	_Copyright
		; Copyright (c) 2006-2012 Noel Henson					Updated: 2007-01-01
Blog
	Noel's Lab #Noel's Lab : Blog#
	_Menu
		[index.html Home]
		//Blog//
		[reviews.html Reviews]
		[howtos.html HOWTOs]
		[software.html Software]
		[links.html Links]
		[contact.html Contact]
	Blog
		2006-10-15 - Simple Remote Control
			: [http://www.infraredremote.com Infrared Remote Solutions, Inc.] 
			: has a cool little relay board the makes it easy to add remote 
			: control to just about anything that uses switches. It runs on 
			: 12VDC so it can be run from a wall wart or from a car's or RV's 
			: power. I'm having a great time with mine. You can get yours 
			: here: [http://www.infraredremote.com/4relay.htm 4-Relay].
			:
			: -- Noel
		2005-11-05 - Troubleshooting Myth
			: Troubleshooting is a rare, innate ability that cannot be taught 
			: nor learned. Right? //Wrong!!!// Here is an excellent page on a real, 
			: teachable and learnable, troubleshooting method that really 
			: works. I have used these and similar techniques for decades.
			:
			: If you are a technician, engineer or regularly deal with system 
			: failures, you should definitely check this out.
			: 	
			: [http://www.troubleshooters.com/tuni.htm The Universal Troubleshooting Process]
			:
			: -- Noel
		2005-10-20 - Vim Outliner rocks!
			: Yes, I know I work on the Vim Outliner project, but that doesn't 
			: take away from VO's usefulness. As a matter of fact, this entire 
			: web site was created with 
			: [http://www.vimoutliner.org Vim Outliner]. This web site is 
			: a single text outline file that is converted into a multi-page 
			: web site with some simple-to-use tools.
			:
			: Yes I also know I created these simple-to-use tools, but that 
			: doesn't mean they're not cool. One tool, otl2html, converts 
			: an outline into an html page. It supports headings, text, 
			: preformatted text, tables with headings and some simple 
			: beautification. You can get this tool from the VO web site: 
			: [http://www.vimoutliner.org www.vimoutliner.org].
			:
			: The other tool, which is not yet available to the public, is 
			: otlsplit. It splits a large outline into several smaller 
			: outlines. I use this tool to split my large website.otl file 
			: into several otl files that will, in turn, be converted to web 
			: pages. Look for this utility to appear soon on the VO website. 
			: Or if you can't wait, you can ask for a copy in the VO mailing 
			: list. You can join the list from the '//Participating//' link on 
			: the VO web site.
			:
			: -- Noel
	_BottomMenu
		[index.html Home] :: [blog.html Blog] :: [reviews.html Reviews] :: [howtos.html HOWTOs] :: [software.html Software] :: [links.html Links] :: [contact.html Contact]
	_Copyright
		; Copyright (c) 2005 Noel Henson					Updated: 2005-11-05
Reviews
	Noel's Lab #Noel's Lab : Reviews#
	_Menu
		[index.html Home]
		[blog.html Blog]
		//Reviews//
		[howtos.html HOWTOs]
		[software.html Software]
		[links.html Links]
		[contact.html Contact]
	Reviews
		: Coming soon!
	_BottomMenu
		[index.html Home] :: [blog.html Blog] :: [reviews.html Reviews] :: [howtos.html HOWTOs] :: [software.html Software] :: [links.html Links] :: [contact.html Contact]
	_Copyright
		; Copyright (c) 2005 Noel Henson					Updated: 2005-10-20
HOWTOs
	Noel's Lab #Noel's Lab : HOWTOs#
	_Menu
		[index.html Home]
		[blog.html Blog]
		[reviews.html Reviews]
		//HOWTOs//
		[software.html Software]
		[links.html Links]
		[contact.html Contact]
	HOWTOs
		: Coming Soon!
	_BottomMenu
		[index.html Home] :: [blog.html Blog] :: [reviews.html Reviews] :: [howtos.html HOWTOs] :: [software.html Software] :: [links.html Links] :: [contact.html Contact]
	_Copyright
		; Copyright (c) 2005 Noel Henson					Updated: 2005-10-20
Software
	Noel's Lab #Noel's Lab : Open Source Software Projects#
	_Menu
		[index.html Home]
		[blog.html Blog]
		[reviews.html Reviews]
		[howtos.html HOWTOs]
		//Software//
			[+http://www.vimoutliner.org Vim Outliner]
			[+otlsplit.html otlsplit]
			[+otlhead.html otlhead]
			[+otltail.html otltail]
			[+otlgrep.html otlgrep]
			[+otl2table.html otl2table]
			[+otl2html.html otl2html]
			[+otl2tags.html otl2tags]
			[+otl2ooimpress.html otl2ooimpress]
			[+cidrmerge.html CIDRmerge]
			[+easybackup.html EasyBackup]
			[+crlf.html crlf]
			[+cordic.html CORDIC Demo]
			[+forthstrings.html Forth Strings]
		[links.html Links]
		[contact.html Contact]
	Software
		: Open souce software projects. My way to give back to the open source 
		: community. OK, I needed the tools for myself but at least I'm 
		: sharing.
		Vim Outliner
			: Vim Outliner is a Vim plugin that makes it behave as 
			: a full-featured outliner of the likes of MaxThink, Grandview, 
			: ThinkTank, and More. It has its own add-ons for checkboxes and 
			: hoisting and is compatible with Vim spell-checkers like vimspell 
			: and engspeak. There are several scripts available from other to 
			: convert text outlines to HTML pages, Docbook files, and Open 
			: Office Impress files.
			:
			: [http://www.vimoutliner.org Vim Outliner details]
		otlsplit
			: Splits an outline into separate outlines according to the 
			: defined split level. Good for creating simple web sites from 
			: a single outline file. Also good for splitting large outines 
			: into smaller outlines like separating an outline of a book into 
			: a bunch of chapter outlines. (see otltail)
			:
			: [+otlsplit.html otlsplit details]
		otlhead
			: Keeps the specified number of outlines levels and removes the 
			: rest. Great for generating summaries, especially when using 
			: checkboxes.
			:
			: [+otlhead.html otlhead details]
		otltail
			: Remove the specified number of parent headings from an outline. 
			: This is a good way to promote children. When used with otl2table 
			: it can aid in extracting information from certain types of 
			: outlines. It can also aid in converting a single outline into 
			: many outlines. (see otlsplit)
			:
			: [+otltail.html otltail details]
		otlgrep
			: This is an outline-aware grep utility. It returns an outline 
			: that contains only branches that satisfy the regular expression. 
			: This is useful for quickly extracting context-sensitive 
			: information from an outline.
			:
			: [+otlgrep.html otlgrep details]
		otl2table
			: Converts an outline into a table in which each branch, all the 
			: way down to it's leaves, is on a single line. Levels are columns 
			: in the table. This is useful for outline-unaware postprocessors 
			: that create new files or extract informations from an outline.
			:
			: [+otl2table.html otl2table details]
		otl2html
			: Converts outline files to pretty html file. Inline and external 
			: CSS is supported. Can be used by Vim Outliner to pretty-print 
			: outlines. (see Vim Outliner)
			:
			: [+otl2html.html otl2html details]
		otl2tags
			: Converts outline files into tags-based output files like HTML, 
			: SGML, XML or whatever. More flexible than otl2html.
			:
			: [+otl2tags.html otl2tags details]
		otl2ooimpress
			: An example utility to convert and outline file into an Open 
			: Office Impress file. It works but the formatting is simple and 
			: hard coded.
			:
			: [+otl2ooimpress.html otl2ooimpress details]
		CIDRmerge
			: Accepts a list of CIDR address blocks and outputs a more 
			: efficient, merged list of CIDR blocks. Useful for simplifying 
			: router configuration when large groups of CIDR blocks are used.
			:
			: [+cidrmerge.html CIDRmerge details]
		EasyBackup
			: An 'easy' backup shell script. Simple include and exclude files 
			: that support wildcards are used to determine what and what not 
			: to backup. Incremental and full backups are implemented as well 
			: as automatic, incremental burning of incremental backups to DVD 
			: (or harddisk). One great advantage of this program is that each 
			: file is individually compressed in an uncompressed hierarchy. 
			: This makes it easy to use any file browser to find the file your 
			: looking for.
			:
			: [+easybackup.html EasyBackup details]
		crlf
			: A shell script that converts text files among the various 
			: formats: unix (LF), PC (CRLF) and Mac (CR). Wildcards are 
			: allowed.
			:
			: [+crlf.html crlf details]
		CORDIC Demo
			: A demonstration of the CORDIC algorithm written in Forth. It 
			: computes sines and cosines in the range of +/-90 degrees. 
			:
			: [+cordic.html CORDIC source]
		Forth Strings Library
			: A super simple strings library for Forth. It has been recently 
			: modified to work with modern Forths like GFORTH.
			:
			: [+forthstrings.html Forth Strings]
	_BottomMenu
		[index.html Home] :: [blog.html Blog] :: [reviews.html Reviews] :: [howtos.html HOWTOs] :: [software.html Software] :: [links.html Links] :: [contact.html Contact]
	_Copyright
		; Copyright (c) 2006 Noel Henson					Updated: 2006-02-13
Links
	Noel's Lab #Noel's Lab : Links#
	_Menu
		[index.html Home]
		[blog.html Blog]
		[reviews.html Reviews]
		[howtos.html HOWTOs]
		[software.html Software]
		//Links//
		[contact.html Contact]
	Links
		Embedded Design and Development
			Lane Mountain Logic - [http://www.lmlogic.com www.lmlogic.com]
				: A shameless plug for my day job. :) Embedded design and 
				: programming services.
		Motion Control
			Infrared Remote Solutions - [http://www.infraredremote.com www.infraredremote.com]
				: Remote controls, remote control receivers/decoders, remote 
				: control relay boards and remote control ICs.
		MCU Boards
			New Micros - [http://www.newmicros.com www.newmicros.com]
				: Excellent, low-cost Boards that speak Forth
		MCU development tools
			picp - [http://home.pacbell.net/theposts/picmicro home.pacbell.net/theposts/picmicro]
				: Linux command-line and GUI interfaces to the 
				: [http://www.microchip.com Microchip] PicStart Plus and other 
				: PIC programmers.
			gputils - [http://gputils.sourceforge.net gputils.sourceforge.net]
				: A collection of tools for the 
				: [http://www.microchip.com Microchip] PIC.
		Test/Lab Equipment
			BitScope - [http://www.bitscope.com www.bitscope.com]
				: Affordable mixed-signal analyzers.
		Thinking
			Vim Outliner - [http://www.vimoutliner.org www.vimoutliner.org]
				: A plugin for Vim that turn it into a complete outliner on 
				: the order of GrandView, More and MaxThink. (This site is 
				: written with Vim Outliner.)
			TroubleShooters.Com&reg; - [http://www.troubleshooters.com www.troubleshooters.com]
				: Loads of information about troubleshooting, planning and 
				: organizing. Techs and engineers should check out the 
				: Universal Troubleshooting Process.
			43 Folders - [http://www.43folders.com www.43folders.com]
				: Great site about organization and productivity.
		Linux
			Distro Watch - [http://www.distrowatch.com www.distrowatch.com]
			Slackware - [http://www.slackware.com www.slackware.com]
	_BottomMenu
		[index.html Home] :: [blog.html Blog] :: [reviews.html Reviews] :: [howtos.html HOWTOs] :: [software.html Software] :: [links.html Links] :: [contact.html Contact]
	_Copyright
		; Copyright (c) 2005 Noel Henson					Updated: 2005-10-22
Contact
	Noel's Lab #Noel's Lab : Contact Information#
	_Menu
		[index.html Home]
		[blog.html Blog]
		[reviews.html Reviews]
		[howtos.html HOWTOs]
		[software.html Software]
		[links.html Links]
		//Contact//
	_Main
		Noel's Lab
			[mailto:noel@noels-lab.com noel@noels-lab.com]
	_BottomMenu
		[index.html Home] :: [blog.html Blog] :: [reviews.html Reviews] :: [howtos.html HOWTOs] :: [software.html Software] :: [links.html Links] :: [contact.html Contact]
	_Copyright
		; Copyright (c) 2006-2012 Noel Henson					Updated: 2007-01-01
		; noel@noels-lab.com

otl2html
Summary
	: Converts an outline to an HTML page or pages. It is used for 'pretty' 
	: printing of outlines, creating portable (inline CSS) documents and even 
	: for creating simple web sites using [otlsplit.html otlsplit].
Usage
	; otl2html.py [options] inputfile > outputfile
	; Options
	;     -p              Presentation: slide show output for use with HtmlSlides.
	;     -D              First-level is divisions (&lt;div&gt; &lt;/div&gt;) for making
	;                     pretty web pages.
	;     -s sheet        Use the specified style sheet with a link. This is the
	;                     default.
	;     -S sheet        Include the specified style sheet in-line the output. For
	;                     encapsulated style.
	;     -T              The first line is not the title. Treat it as outline data
	;     -c              comments (line with [ as the first non-whitespace
	;                     character. Ending with ] is optional.
	;     -C copyright    Override the internal copyright notice with the
	;                     one supplied in the quoted string following this
	;                     flag. Single or double quotes can be used.
	;     -v              Print version (RCS) information.
	;     -H              Show the file syntax help.
	; output is on STDOUT
	;   Note: if neither -s or -S are specified, otl2html.py will default to -s. It
	;       will try to use the css file 'nnnnnn.css' if it exists. If it does not
	;       exist, it will be created automatically.
Syntax
	; Syntax is Vim Outliner's normal syntax. The following are supported:
	; 
	;    Text
	;         :       Body text marker. This text will wrap in the output.
	;         ;       Preformmated text. This text will will not wrap.
	; 
	;    Tables
	;         ||      Table header line.
	;         |       Table and table columns. Example:
	;                         || Name | Age | Animal |
	;                         | Kirby | 9 | Dog |
	;                         | Sparky | 1 | Bird |
	;                         | Sophia | 8 | Cat |
	;                         This will cause an item to be left-justified.
	;                                 | whatever  |
	;                         This will cause an item to be right-justified.
	;                                 |  whatever |
	;                         This will cause an item to be centered.
	;                                 | whatever |
	; 
	;    Character Styles
	;         &#42;&#42;      Bold. &#42;&#42;Bold Text&#42;&#42; yields **Bold Text**
	;         &#47;&#47;      Italic. &#47;&#47;Italic Text&#47;&#47; yields //Italic Text//
	;         &#43;&#43;&#43;     Highlight. &#43;&#43;&#43;Highlight Text&#43;&#43;&#43; yields +++Highlight Text+++
	;         &#45;&#45;&#45;     Strikeout. &#45;&#45;&#45;Strikeout Text&#45;&#45;&#45; yields <strike>Strikeout Text</strike>
	;         Insane  &#45;&#45;&#45;&#43;&#43;&#43;&#47;&#47;&#42;&#42;Wow! This is insane!&#42;&#42;&#47;&#47;&#43;&#43;&#43;&#45;&#45;&#45; yields <strike>+++//**Wow! This is insane!**//+++</strike>
	;                 Just remember to keep it all on one line.
	;    Horizontal Rule
	;         ----------------------------------------  (40 dashes).
	;    Copyright
	;         &#40;c) or &#40;C)      Converts to a standard copyright symbol (c).
	; 
	;    Including Images (for web pages)
	;         &#91;imagename]     Examples:
	;                         &#91;logo.gif] &#91;photo.jpg] &#91;car.png]
	;                         &#91;http://i.a.cnn.net/cnn/.element/img/1.1/logo/logl.gif]
	;                         or from a database:
	;                         &#91;http://www.lab.com/php/image.php?id=4]
	; 
	;    Including links (for web pages)
	;         &#91;link text-or-image]    Examples:
	;                         &#91;about.html About] &#91;http:&#47;&#47;www.cnn.com CNN]
	;                         or with an image:
	;                         &#91;http:&#47;&#47;www.ted.com &#91;http:&#47;&#47;www.ted.com&#47;logo.png]]
	; 
	;    Note:
	;         When using -D, the top-level headings become divisions (&lt;div>)
	;         and will be created using a class of the heading name. Spaces
	;         are not allowed. If a top-level heading begins with '_', it
	;         will not be shown but the division name will be the same as
	;         without the '_'. Example: _Menu will have a division name of
	;         Menu and will not be shown.
Examples
	: This page and all of the pages of this web site were created with 
	: otl2html.
Downloads
	[http://www.noels-lab.com/files/otl2html.zip Download ZIP]
	[http://www.noels-lab.com/files/otl2html.tgz Download tgz]
License
	: This program is free software; you can redistribute it and/or modify
	: it under the terms of the GNU General Public License as published by
	: the Free Software Foundation; either version 2 of the License.
	:
	: This program is distributed in the hope that it will be useful,
	: but WITHOUT ANY WARRANTY; without even the implied warranty of
	: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	: GNU General Public License for more details.
	:
	: You should have received a copy of the GNU General Public License
	: along with this program; if not, write to the Free Software
	: Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Credits
	; Copyright (c) 2006 Noel Henson					Updated: 2006-04-21
	; noel@noels-lab.com

**Comment by mcepl** [comment]
OK, so the result of this issue is:
1) --help and -H should be same (and we should probably switch to using `argparse` so all help stuff is handled reasonably)
2) we should add `<meta charset="utf-8">` to the `<head>` element, so that `otl2html` is also useful for somebody else than #@## Americans.

**Comment by noelhenson** [comment]
Here is how it should be done:

-h, --help
-H one learns about if they read the -h or --help output. ;)

I should definitely add --help-syntax.

Also I need to include some of the other processing features.

Good idea on the <head> element. It should be specifiable in the command 
line options.

otl2tags does a much better job of that. And it can be configured via 
configuration files. otl2html, believe it or not, was initially a hack 
so I could write and online and printed presentation that used 
HTMLslides (courtesy of Steve Litt). It was taking my staff way too long 
to do it in Word and/or PowerPoint.

LOL I kind of grew out of that so I could write a website and stay in VO.

otl2tags was an attempt to fix all that and handle just about any kind 
of tag-related markup one might want.

**Comment by mcepl** [comment]
@noelhenson ???

**Comment by noelhenson** [comment]
This has been addressed before. The best solution was to use another vim 
plugin that is already programmed for highlighting URLs.

**Comment by mcepl** [comment]
Please review this pull request (#118).
Still not using `argparse` and still not producing validating HTML5 pages, but a step ahead.

**Comment by mcepl** [comment]
When I say still broken, I mean 

[Showing results for uploaded file rodinna_ubytovani.html - Nu Html Checker.html.txt](https://github.com/vimoutliner/vimoutliner/files/973043/Showing.results.for.uploaded.file.rodinna_ubytovani.html.-.Nu.Html.Checker.html.txt)
